### ISSUE TITLE
After manually Grouping Versions Cause's lockup

### ISSUE THREAD

**Issue by sbcrumb** [danieladov/jellyfin-plugin-mergeversions#2]
If I manually select 2 movies and I group them, the following error is thrown and it will no longer scroll past the movies.

[2020-07-08 09:36:18.832 -04:00] [ERR] [1] App: Error creating "Jellyfin.Plugin.MergeVersions.MergeVersionsManager"
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.MergeVersions.Api.GetId' while attempting to activate 'Jellyfin.Plugin.MergeVersions.MergeVersionsManager'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2020-07-08 09:36:18.942 -04:00] [INF] [1] App: Executed all pre-startup entry points in 0:00:00.1017425
[2020-07-08 09:36:18.942 -04:00] [INF] [1] App: Core startup complete

**Comment by danieladov** [comment]
I'm not sure why does this happen, the plugin shouldn't do anything while merging manually two movies.
Did you try to execute the plugin through scheduled tasks?

**Comment by sbcrumb** [comment]
I did run it manually.. And some of the same movies wouldn't merge no idea why then when I did them manually with the Group Versions it would cause the hang.. So I finally deleted that library and started over. Waited manually matched the ones it missed, then ran your plug in.. so far I think it is ok.

**Comment by danieladov** [comment]
There's a bug at 10.5.5 wich corrupts the database if you merge 2 movies 2 times (https://github.com/jellyfin/jellyfin/issues/3176). This has been fixed in the new version of Jellyfin
