### ISSUE TITLE
Update for jellyfin 10.8.0

### ISSUE THREAD

**Issue by ToastKiste21** [danieladov/jellyfin-plugin-mergeversions#21]
The Plugin don't work on jellyfin server 10.8.0.

**Comment by nathanvdh** [comment]
Here's log:

`[2021-12-04 03:08:05.940 +00:00] [INF] [33] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 POST http://192.168.1.34:8096/MergeVersions/MergeMovies - 0
[2021-12-04 03:08:05.941 +00:00] [INF] [33] Microsoft.AspNetCore.Cors.Infrastructure.CorsService: CORS policy execution successful.
[2021-12-04 03:08:05.945 +00:00] [INF] [33] Microsoft.AspNetCore.Routing.EndpointMiddleware: Executing endpoint '"Jellyfin.Plugin.MergeVersions.Api.MergeVersionsController.MergeMoviesRequest (Jellyfin.Plugin.MergeVersions)"'
[2021-12-04 03:08:05.948 +00:00] [INF] [33] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Route matched with "{action = \"MergeMoviesRequest\", controller = \"MergeVersions\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.ActionResult MergeMoviesRequest()" on controller "Jellyfin.Plugin.MergeVersions.Api.MergeVersionsController" ("Jellyfin.Plugin.MergeVersions").
[2021-12-04 03:08:05.952 +00:00] [INF] [33] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Executed action "Jellyfin.Plugin.MergeVersions.Api.MergeVersionsController.MergeMoviesRequest (Jellyfin.Plugin.MergeVersions)" in 2.9492ms
[2021-12-04 03:08:05.953 +00:00] [INF] [33] Microsoft.AspNetCore.Routing.EndpointMiddleware: Executed endpoint '"Jellyfin.Plugin.MergeVersions.Api.MergeVersionsController.MergeMoviesRequest (Jellyfin.Plugin.MergeVersions)"'
[2021-12-04 03:08:05.957 +00:00] [ERR] [33] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/MergeVersions/MergeMovies".
System.MissingMethodException: Method not found: 'Void Jellyfin.Api.Controllers.VideosController..ctor(MediaBrowser.Controller.Library.ILibraryManager, MediaBrowser.Controller.Library.IUserManager, MediaBrowser.Controller.Dto.IDtoService, MediaBrowser.Controller.Dlna.IDlnaManager, MediaBrowser.Controller.Net.IAuthorizationContext, MediaBrowser.Controller.Library.IMediaSourceManager, MediaBrowser.Controller.Configuration.IServerConfigurationManager, MediaBrowser.Controller.MediaEncoding.IMediaEncoder, MediaBrowser.Model.IO.IFileSystem, MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder, Microsoft.Extensions.Configuration.IConfiguration, MediaBrowser.Controller.Devices.IDeviceManager, Jellyfin.Api.Helpers.TranscodingJobHelper, System.Net.Http.IHttpClientFactory)'.
   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager..ctor(ILibraryManager libraryManager, ICollectionManager collectionManager, ILogger`1 logger, IServerConfigurationManager serverConfigurationManager, IUserManager userManager, IDtoService dtoService, IAuthorizationContext authContext, IFileSystem fileSystem, IDlnaManager dlnaManager, IMediaSourceManager mediaSourceManager, IMediaEncoder mediaEncoder, ISubtitleEncoder subtitleEncoder, IDeviceManager deviceManager, TranscodingJobHelper transcodingJobHelper)
   at Jellyfin.Plugin.MergeVersions.Api.MergeVersionsController..ctor(ILibraryManager libraryManager, ICollectionManager collectionManager, ILogger`1 logger, IServerConfigurationManager serverConfigurationManager, IUserManager userManager, IDtoService dtoService, IAuthorizationContext authContext, IFileSystem fileSystem, IDlnaManager dlnaManager, IMediaSourceManager mediaSourceManager, IMediaEncoder mediaEncoder, ISubtitleEncoder subtitleEncoder, IDeviceManager deviceManager, TranscodingJobHelper transcodingJobHelper)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)`

**Comment by danieladov** [comment]
I've just released a new version for 10.8

**Comment by nathanvdh** [comment]
Awesome thanks for your work, appreciate it muchly.
