### ISSUE TITLE
Not compatibvle with 10.9

### ISSUE THREAD

**Issue by memehammad** [danieladov/jellyfin-plugin-mergeversions#53]
Hey, just letting you know that your plugin isn't compatible with the latest 10.9 beta.

This is the error:

> [2024-04-21 09:39:20.511 +02:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/data/plugins/Merge Versions_10.8.0.2/Jellyfin.Plugin.MergeVersions.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
> Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
>    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
>    at System.Reflection.RuntimeModule.GetTypes()
>    at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
> System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by n00mkrad** [comment]
+1

I tried to update it but couldn't really figure it out

**Comment by sendarion** [comment]
Hello, does it work with the 10.9 stable release?

**Comment by sendarion** [comment]
Sad, thank you for answering

**Comment by danieladov** [comment]
Hi, I will try to release a working version tomorrow

**Comment by danieladov** [comment]
I've just released an update. Please let me know if it's working for you.

**Comment by Hunter-Clipper** [comment]
> I've just released an update. Please let me know if it's working for you.

Looks to work for me on JF v.10.9.1

**Comment by sendarion** [comment]
Thank you very much for your quick response <3
