### ISSUE TITLE
10.9.1 Unhandled Exception

### ISSUE THREAD

**Issue by slimshizn** [danieladov/jellyfin-plugin-mergeversions#55]
Latest merge versions update and Jellyfin 10.9.1

Getting database locks at some points. Here's the docker logs:

```
[20:38:44] [INF] [54] Jellyfin.Plugin.MergeVersions.MergeVersionsManager: Merging Tinker Bell and the Pirate Fairy (2014)
[20:38:44] [FTL] [53] Main: Unhandled Exception
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Emby.Server.Implementations.Data.SqliteItemRepository'.
   at Emby.Server.Implementations.Data.SqliteItemRepository.RetrieveItem(Guid id)
   at Emby.Server.Implementations.Library.LibraryManager.GetItemById(Guid id)
   at Emby.Server.Implementations.Library.LibraryManager.GetItemById[T](Guid id)
   at Emby.Server.Implementations.Library.LibraryManager.GetItemById[T](Guid id, User user)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager.MergeVersions(List`1 ids)
   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager.<>c__DisplayClass6_0.<<MergeMovies>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[20:38:44] [INF] [54] Jellyfin.Plugin.MergeVersions.MergeVersionsManager: Merging The Hate U Give (2018)
[20:38:44] [INF] [54] Jellyfin.Plugin.MergeVersions.MergeVersionsManager: Merging Ghostmates (2016)
[20:38:44] [INF] [54] Jellyfin.Plugin.MergeVersions.MergeVersionsManager: Merging A Family Reunion Christmas (2019)
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Emby.Server.Implementations.Data.SqliteItemRepository'.
   at Emby.Server.Implementations.Data.SqliteItemRepository.RetrieveItem(Guid id)
   at Emby.Server.Implementations.Library.LibraryManager.GetItemById(Guid id)
   at Emby.Server.Implementations.Library.LibraryManager.GetItemById[T](Guid id)
   at Emby.Server.Implementations.Library.LibraryManager.GetItemById[T](Guid id, User user)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager.MergeVersions(List`1 ids)
   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager.<>c__DisplayClass6_0.<<MergeMovies>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[20:38:44] [INF] [54] Jellyfin.Plugin.MergeVersions.MergeVersionsManager: Merging Cars 3 (2017)
[20:38:44] [INF] [54] Jellyfin.Plugin.MergeVersions.MergeVersionsManager: Merging The Legend Of Wasco (2015)
```

**Comment by SkalCore** [comment]
same here

```stdout
17.05.2024
10:19:51
[08:19:50] [FTL] [18] Main: Unhandled Exception
stdout
17.05.2024
10:19:51
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database table is locked'.
stdout
17.05.2024
10:19:51
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
stdout
17.05.2024
10:19:51
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
stdout
17.05.2024
10:19:51
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
stdout
17.05.2024
10:19:51
   at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel, Boolean deferred)
stdout
17.05.2024
10:19:51
   at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel, Boolean deferred)
stdout
17.05.2024
10:19:51
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveImages(BaseItem item)
stdout
17.05.2024
10:19:51
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
stdout
17.05.2024
10:19:51
   at Emby.Server.Implementations.Library.LibraryManager.RunMetadataSavers(BaseItem item, ItemUpdateType updateReason)
stdout
17.05.2024
10:19:51
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
stdout
17.05.2024
10:19:51
   at MediaBrowser.Controller.Entities.Video.UpdateToRepositoryAsync(ItemUpdateType updateReason, CancellationToken cancellationToken)
stdout
17.05.2024
10:19:51
   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager.MergeVersions(List`1 ids)
stdout
17.05.2024
10:19:51
   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager.<>c__DisplayClass6_0.<<MergeMovies>b__2>d.MoveNext()
stdout
17.05.2024
10:19:51
--- End of stack trace from previous location ---
stdout
17.05.2024
10:19:51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
stdout
17.05.2024
10:19:51
   at System.Threading.QueueUserWorkItemCallback.Execute()
stdout
17.05.2024
10:19:51
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
stdout
17.05.2024
10:19:51
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
stderr
17.05.2024
10:19:51
Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database table is locked'.
stderr
17.05.2024
10:19:51
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
stderr
17.05.2024
10:19:51
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
stderr
17.05.2024
10:19:51
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
stderr
17.05.2024
10:19:51
   at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel, Boolean deferred)
stderr
17.05.2024
10:19:51
   at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel, Boolean deferred)
stderr
17.05.2024
10:19:51
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveImages(BaseItem item)
stderr
17.05.2024
10:19:51
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
stderr
17.05.2024
10:19:51
   at Emby.Server.Implementations.Library.LibraryManager.RunMetadataSavers(BaseItem item, ItemUpdateType updateReason)
stderr
17.05.2024
10:19:51
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
stderr
17.05.2024
10:19:51
   at MediaBrowser.Controller.Entities.Video.UpdateToRepositoryAsync(ItemUpdateType updateReason, CancellationToken cancellationToken)
stderr
17.05.2024
10:19:51
   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager.MergeVersions(List`1 ids)
stderr
17.05.2024
10:19:51
   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager.<>c__DisplayClass6_0.<<MergeMovies>b__2>d.MoveNext()
stderr
17.05.2024
10:19:51
--- End of stack trace from previous location ---
stderr
17.05.2024
10:19:51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
stderr
17.05.2024
10:19:51
   at System.Threading.QueueUserWorkItemCallback.Execute()
stderr
17.05.2024
10:19:51
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
stderr
17.05.2024
10:19:51
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
stdout
17.05.2024
10:19:57
[08:19:57] [INF] [1] Main: Jellyfin version: 10.9.1```

crashed jellyfin

**Comment by danieladov** [comment]
Hi, does this also happen with version 10.9.1.0  (last one is 10.9.1.1)

**Comment by SkalCore** [comment]
> Hi, does this also happen with version 10.9.1.0 (last one is 10.9.1.1)

use docker, the latest version there is 10.9.1.0, no new update in stable branch actual found

**Comment by SkalCore** [comment]
> > > Hi, does this also happen with version 10.9.1.0 (last one is 10.9.1.1)
> > 
> > 
> > use docker, the latest version there is 10.9.1.0, no new update in stable branch actual found
> 
> I mean the plugin version

sorry, got it wrong plugin Version is 10.9.1.1, splitting has been working for over an hour now, error occurs when several films about planned tasks are to be merged
