### ISSUE TITLE
Jellyfin 10.9.8 Crash while running mergeversions

### ISSUE THREAD

**Issue by slimshizn** [danieladov/jellyfin-plugin-mergeversions#61]
```
 at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()

   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager+<>c.<MergeVersions>b__12_2(MediaBrowser.Controller.Entities.Video)

   at System.Linq.Enumerable.TryGetFirst[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>, Boolean ByRef)

   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager+<MergeVersions>d__12.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Jellyfin.Plugin.MergeVersions.MergeVersionsManager+<MergeVersions>d__12, Jellyfin.Plugin.MergeVersions, Version=10.9.1.1, Culture=neutral, PublicKeyToken=null]](<MergeVersions>d__12 ByRef)

   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager.MergeVersions(System.Collections.Generic.List`1<System.Guid>)

   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager+<>c__DisplayClass6_0+<<MergeMovies>b__2>d.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Jellyfin.Plugin.MergeVersions.MergeVersionsManager+<>c__DisplayClass6_0+<<MergeMovies>b__2>d, Jellyfin.Plugin.MergeVersions, Version=10.9.1.1, Culture=neutral, PublicKeyToken=null]](<<MergeMovies>b__2>d ByRef)

   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager+<>c__DisplayClass6_0.<MergeMovies>b__2(System.Linq.IGrouping`2<System.String,MediaBrowser.Controller.Entities.Movies.Movie>)

   at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int64, Boolean ByRef)

   at System.Threading.Tasks.TaskReplicator+Replica.Execute()

   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   ```

**Comment by Panda260** [comment]
Hey i get the same error.


   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at MediaBrowser.Controller.Entities.Video.get_MediaSourceCount()
   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager+<>c.<MergeVersions>b__12_2(MediaBrowser.Controller.Entities.Video)
   at System.Linq.Enumerable.TryGetFirst[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>, Boolean ByRef)
   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager+<MergeVersions>d__12.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Jellyfin.Plugin.MergeVersions.MergeVersionsManager+<MergeVersions>d__12, Jellyfin.Plugin.MergeVersions, Version=10.9.1.1, Culture=neutral, PublicKeyToken=null]](<MergeVersions>d__12 ByRef)
   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager.MergeVersions(System.Collections.Generic.List`1<System.Guid>)
   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager+<>c__DisplayClass6_0+<<MergeMovies>b__2>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Jellyfin.Plugin.MergeVersions.MergeVersionsManager+<>c__DisplayClass6_0+<<MergeMovies>b__2>d, Jellyfin.Plugin.MergeVersions, Version=10.9.1.1, Culture=neutral, PublicKeyToken=null]](<<MergeMovies>b__2>d ByRef)
   at Jellyfin.Plugin.MergeVersions.MergeVersionsManager+<>c__DisplayClass6_0.<MergeMovies>b__2(System.Linq.IGrouping`2<System.String,MediaBrowser.Controller.Entities.Movies.Movie>)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int64, Boolean ByRef)
   at System.Threading.Tasks.TaskReplicator+Replica.Execute()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
[20:57:08] [INF] [1] Main: Jellyfin version: 10.9.9

**Comment by Panda260** [comment]
![image](https://github.com/user-attachments/assets/63f87f4d-11ef-4b65-9bff-1106c9d06210)

**Comment by Zachwang007** [comment]
me too, with jellyfin 10.9.11 ,when open  this plugs,after 1 or 2mins ,the jellyfin server crashed.when disable this plug ,the jellyfin server works well
