### ISSUE TITLE
Can't install latest version from the repo or the manual method

### ISSUE THREAD

**Issue by kstbh-sys** [danieladov/jellyfin-plugin-mergeversions#8]
This is the error I found in the logs while installing plugin from the repo.
```
[2020-12-05 18:36:22.696 +00:00] [ERR] Error processing request. URL: "http://MyIP:8096/Packages/Installed/Merge Versions?AssemblyGuid=f21bbed8-3a97-4d8b-88b2-48aaa65427cb&version=10.7.0"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Merge Versions
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by danieladov** [comment]
That's weird, are you using 10.7.0? If you are updating try to delete the previous version manually first.

**Comment by intertan** [comment]
> That's weird, are you using 10.7.0? If you are updating try to delete the previous version manually first.

having the same issue on a fresh unraid docker install. Latest version will not install

**Comment by danieladov** [comment]
I've just tried in a new docker and is working perfectly, are you sure you have the last jellyfin version (10.7.0)?

**Comment by kstbh-sys** [comment]
nvm, I was trying to install it on 10.6.4. Updated to 10.7.0 and it got installed.
