### ISSUE TITLE
Exception with 10.7.0-rc2

### ISSUE THREAD

**Issue by peterbaumert** [danieladov/jellyfin-plugin-mergeversions#9]
```
System.TypeLoadException: Could not load type 'MediaBrowser.Model.Services.IReturn`1' from assembly 'MediaBrowser.Model, Vers
ion=10.7.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()
   at Emby.Server.Implementations.ApplicationHost.Init()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
```

When this plugin is loaded i always get up exception and jellyfin server wont start.

KR
Pete

**Comment by peterbaumert** [comment]
sorry wrong plugin
